/* eslint-disable import/prefer-default-export */
export const blogs = [
  {
    tabType: 'articles',
    tabTitle: 'Car Buying Tips and Guides',
    active: true,
    tabId: 'tab1',
    tabContent: {
      header: '',
      cardData: [
        {
          id: 'Article1',
          heading: '',
          title: 'What Documents Do I Need To Purchase A Vehicle?',
          description: 'Purchasing a vehicle requires a ton of paperwork that can slow the process down if you aren’t prepared. Here are six items to bring with you to the dealership.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/stack-of-documents-to-bring-to-car-dealership-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/stack-of-documents-to-bring-to-car-dealership-tab.webp',
          imgAlt: 'What Documents Do I Need To Purchase A Vehicle?',
          cardButton: {
            target: '',
            url: '/blog/consumer/what-documents-do-i-need-to-purchase-a-vehicle-',
            label: 'Read >',
          },
        },
        {
          id: 'Article2',
          heading: '',
          title: 'How To Trade In Your Car',
          description: 'Making plans on trading in your car soon? Here are several things you should know before you get the ball rolling.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/close-up-handing-car-keys-to-car-dealer-lg.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/close-up-handing-car-keys-to-car-dealer-tab.webp',
          imgAlt: 'How To Trade In Your Car',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-trade-in-your-car',
            label: 'Read >',
          },
        },
        {
          id: 'Article3',
          heading: '',
          title: 'Getting Car Insurance: 5 Things To Consider',
          description: 'Shopping for a car involves shopping for the right auto insurance policy for you. Here are five factors to consider when searching for car insurance.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/driver-signs-document-next-to-two-cars-that-have-collided-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/driver-signs-document-next-to-two-cars-that-have-collided-tab.webp',
          imgAlt: 'Getting Car Insurance: 5 Things To Consider',
          cardButton: {
            target: '',
            url: '/blog/consumer/getting-car-insurance-5-things-to-consider',
            label: 'Read >',
          },
        },
        {
          id: 'Article4',
          heading: '',
          title: 'Can I Buy A Car With No Down Payment',
          description: 'While buying a car with no down payment may sound appealing, it could result in you paying a higher monthly car payment. Here’s what you should know.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/man-looks-at-car-he-is-considering-purchasing-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/man-looks-at-car-he-is-considering-purchasing-tab.webp',
          imgAlt: 'Can I Buy A Car With No Down Payment',
          cardButton: {
            target: '',
            url: '/blog/consumer/can-i-buy-a-car-with-no-down-payment-',
            label: 'Read >',
          },
        },
        {
          id: 'Article5',
          heading: '',
          title: 'Factors to Consider When Buying a Car',
          description: 'Usage, quality, reliability and the total cost of ownership are all important factors to consider when buying a car.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/factors-to-consider-when-buying-a-car-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/factors-to-consider-when-buying-a-car-tab.webp',
          imgAlt: 'Factors to Consider When Buying a Car',
          cardButton: {
            target: '',
            url: '/car-buyers/express-lane/factors-when-choosing-a-car',
            label: 'Read >',
          },
        },
        {
          id: 'Article6',
          heading: '',
          title: 'Can I Buy A Car After Bankruptcy',
          description: 'It’s not impossible to buy a car after bankruptcy—you just need to know the right steps to take. Read to learn more!',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/close-up-hand-holding-toy-car-and-keys-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/close-up-hand-holding-toy-car-and-keys-tab.webp',
          imgAlt: 'Can I Buy A Car After Bankruptcy',
          cardButton: {
            target: '',
            url: '/blog/consumer/can-i-buy-a-car-after-bankruptcy-',
            label: 'Read >',
          },
        },
        {
          id: 'Article7',
          heading: '',
          title: 'Know Car Insurance Fees When Buying A Car',
          description: 'To help you determine the best approach to evaluating the potential cost of car insurance, here are some simple steps you can follow to get car insurance estimates.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/Estimate-Car-Insurance-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/Estimate-Car-Insurance-tab.webp',
          imgAlt: 'Know Car Insurance Fees When Buying A Car',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-estimate-your-car-insurance-costs-before-purchasing-a-vehicle',
            label: 'Read >',
          },
        },
        {
          id: 'Article8',
          heading: '',
          title: 'How To Narrow Down Your Options When Shopping For A Car',
          description: 'Making the right decision can be overwhelming — we get it. That’s why we compiled a list of ways you can narrow down your options while car shopping.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/many-cars-parked-in-dealership-lot-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/many-cars-parked-in-dealership-lot-tab.webp',
          imgAlt: 'How To Narrow Down Your Options When Shopping For A Car',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-narrow-down-your-options-when-shopping-for-a-car',
            label: 'Read >',
          },
        },
        {
          id: 'Article9',
          heading: '',
          title: 'Is Now The Right Time For You To Buy A Car?',
          description: 'With used and new car inventory making a slow recovery, analysts predict the best time to buy a car in 2022. Learn more!',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/man-holds-key-to-new-car-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/man-holds-key-to-new-car-tab.webp',
          imgAlt: 'Is Now The Right Time For You To Buy A Car?',
          cardButton: {
            target: '',
            url: '/blog/consumer/is-now-the-right-time-for-you-to-buy-a-car-',
            label: 'Read >',
          },
        },
        {
          id: 'Article10',
          heading: '',
          title: 'Long-Lasting Vehicles Of 2021',
          description: 'While you may not be planning on driving 200,000 miles, you may be buying a used car that already has miles on it. Knowing there are vehicles that have this type of longevity with the proper maintenance can be reassuring when shopping for used vehicles.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/various-cars-on-a-car-lot-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/various-cars-on-a-car-lot-tab.webp',
          imgAlt: 'Long-Lasting Vehicles Of 2021',
          cardButton: {
            target: '',
            url: '/blog/consumer/long-lasting-vehicles-of-2021',
            label: 'Read >',
          },
        },
        {
          id: 'Article11',
          heading: '',
          title: 'Used Car Buying Resources',
          description: 'Are you looking to buy a used car? Here are five resources that can help you during your used car search!',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/young-man-concentrates-at-computer-screen-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/young-man-concentrates-at-computer-screen-tab.webp',
          imgAlt: 'Used Car Buying Resources',
          cardButton: {
            target: '',
            url: '/blog/consumer/used-car-buying-resources',
            label: 'Read >',
          },
        },
        {
          id: 'Article12',
          heading: '',
          title: 'What’s The Better Buy: All-Wheel Or Front Wheel',
          description: 'As you’re navigating the car buying process and weighing your options, here are some factors to consider regarding front-wheel and all-wheel drive.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/close-up-of-vehicle-tire-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/close-up-of-vehicle-tire-tab.webp',
          imgAlt: 'What’s The Better Buy: All-Wheel Or Front Wheel',
          cardButton: {
            target: '',
            url: '/blog/consumer/what-s-the-better-buy-all-wheel-or-front-wheel-',
            label: 'Read >',
          },
        },
        {
          id: 'Article13',
          heading: '',
          title: 'Gas Vs. Electric Car Facts',
          description: 'Perhaps you want to know which type of car is more cost-effective in the long run or want to help reduce emissions. Once you have a good grasp on the basics of hybrid and electric vehicles, you’ll have a better understanding of whether a gas, diesel, or electric vehicle is best for you.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/gas-nozzle-and-electric-car-plug-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/gas-nozzle-and-electric-car-plug-tab.webp',
          imgAlt: 'Gas Vs. Electric Car Facts',
          cardButton: {
            target: '',
            url: '/blog/consumer/gas-vs-electric-car-facts',
            label: 'Read >',
          },
        },
        {
          id: 'Article14',
          heading: '',
          title: 'The Advantages of Hybrid Cars',
          description: 'Understanding how hybrid cars work, why they increase fuel economy and the advantages they bring to new owners.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/AdvantagesofHybridCars-SmallArticleImage.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/AdvantagesofHybridCars-TabletArticleImage.webp',
          imgAlt: 'The Advantages of Hybrid Cars',
          cardButton: {
            target: '',
            url: '/car-buyers/express-lane/benefits-of-gas-hybrid-and-electric-vehicles',
            label: 'Read >',
          },
        },
        {
          id: 'Article15',
          heading: '',
          title: 'Pros And Cons Of Online Car Shopping',
          description: 'As the digital world continues to evolve and time and convenience become more of a priority, consumers are becoming more comfortable with online shopping – from groceries, to clothing, to cars, and the list goes on.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/man-on-ipad-shops-for-vehicle-in-coffee-shop-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/man-on-ipad-shops-for-vehicle-in-coffee-shop-tab.webp',
          imgAlt: 'Pros And Cons Of Online Car Shopping',
          cardButton: {
            target: '',
            url: '/blog/consumer/pros-and-cons-of-online-car-shopping',
            label: 'Read >',
          },
        },
        {
          id: 'Article16',
          heading: '',
          title: 'What To Know Before Buying A Car',
          description: 'Buying a car is a major decision and investment, so it’s good to be prepared before you go into the car buying process. Here’s what you should know!',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/woman-holds-key-fob-in-front-of-new-car-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/woman-holds-key-fob-in-front-of-new-car-tab.webp',
          imgAlt: 'What To Know Before Buying A Car',
          cardButton: {
            target: '',
            url: '/blog/consumer/what-to-know-before-buying-a-car',
            label: 'Read >',
          },
        },
        {
          id: 'Article17',
          heading: '',
          title: 'Does My Employment Status Impact My Ability To Buy A Car',
          description: "If you have bad credit or no credit, you most likely will need to provide proof of income to get credit approval during the car-buying process. Here's why.",
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/does-my-employment-status-impact-my-ability-to-buy-a-car-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/does-my-employment-status-impact-my-ability-to-buy-a-car-tab.webp',
          imgAlt: 'Does My Employment Status Impact My Ability To Buy A Car',
          cardButton: {
            target: '',
            url: '/blog/consumer/does-my-employment-status-impact-my-ability-to-buy-a-car-',
            label: 'Read >',
          },
        },
        {
          id: 'Article18',
          heading: '',
          title: 'Checking The Vehicle History Report On A Used Car',
          description: 'A wealth of useful information can be found in a vehicle history report to help you make an informed decision about the used car you’re considering. Here are several pieces of information you should look for when checking a vehicle history report.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/woman-checking-vehicle-history-on-computer-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/woman-checking-vehicle-history-on-computer-tab.webp',
          imgAlt: 'Checking The Vehicle History Report On A Used Car',
          cardButton: {
            target: '',
            url: '/blog/consumer/checking-the-vehicle-history-report-on-a-used-car',
            label: 'Read >',
          },
        },
        {
          id: 'Article19',
          heading: '',
          title: 'Used Cars Under $10K For First-Time Car Buyers On A Budget',
          description: 'While buying your first car is exciting, it’s also a major investment. Check out these five reliable used cars for first time car buyers under $10K!',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/car-salesman-shows-customer-used-vehicle-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/car-salesman-shows-customer-used-vehicle-tab.webp',
          imgAlt: 'Used Cars Under $10K For First-Time Car Buyers On A Budget',
          cardButton: {
            target: '',
            url: '/blog/consumer/used-cars-under-10k-for-first-time-car-buyers-on-a-budget',
            label: 'Read >',
          },
        },
        {
          id: 'Article20',
          heading: '',
          title: 'Buying A Car Out Of State: What To Know',
          description: 'A major perk of the Internet and modern technology is that it gives car shoppers the ability to search for vehicles online, which means there’s a possibility you may find your perfect car out of state.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/couple-speaks-to-dealer-in-front-of-new-car-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/couple-speaks-to-dealer-in-front-of-new-car-tab.webp',
          imgAlt: 'Buying A Car Out Of State: What To Know',
          cardButton: {
            target: '',
            url: '/blog/consumer/buying-a-car-out-of-state-what-to-know',
            label: 'Read >',
          },
        },
        {
          id: 'Article21',
          heading: '',
          title: 'Top Family Cars & Suvs To Consider When Car Buying',
          description: 'Whether your family needs more cargo space for a car seat or stroller, or the latest tech and teen driver features, there’s something out there for everyone.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/car-dealer-hands-happy-family-key-to-new-car-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/car-dealer-hands-happy-family-key-to-new-car-tab.webp',
          imgAlt: 'Top Family Cars & Suvs To Consider When Car Buying',
          cardButton: {
            target: '',
            url: '/blog/consumer/top-family-cars-suvs-to-consider-when-car-buying',
            label: 'Read >',
          },
        },
        {
          id: 'Article22',
          heading: '',
          title: 'Why You Should Choose An Enrolled Dealer',
          description: 'Choosing a dealer enrolled in the Credit Acceptance program can give you a fresh start to building or reestablishing your credit. Here are a few ways Credit Acceptance can be beneficial for you during your financial journey.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/18 choosing_a_Credit_Acceptance_dealer-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/18 choosing_a_Credit_Acceptance_dealer-tab.webp',
          imgAlt: 'Why You Should Choose An Enrolled Dealer',
          cardButton: {
            target: '',
            url: '/blog/consumer/3-simple-steps-to-start-your-approval-for-your-next-c-1',
            label: 'Read >',
          },
        },
        {
          id: 'Article23',
          heading: '',
          title: '4 Things First-Time Drivers Should Know',
          description: 'First-time drivers should plan their route in advance, adjust the car’s mirrors and seat, eliminate distractions and then relax and enjoy the drive.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/4-things-first-time-drivers-should-know-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/4-things-first-time-drivers-should-know-tab.webp',
          imgAlt: '4 Things First-Time Drivers Should Know',
          cardButton: {
            target: '',
            url: '/blog/consumer/4-things-first-time-car-drivers-should-kn-1',
            label: 'Read >',
          },
        },
        {
          id: 'Article24',
          heading: '',
          title: '7 Common Used Car Buying Mistakes',
          description: 'Here are 7 common used car buying mistakes that first-time car buyers should avoid, from lack of preparation to failing to understanding auto financing.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/7-common-used-car-buying-mistakes-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/7-common-used-car-buying-mistakes-tab.webp',
          imgAlt: '7 Common Used Car Buying Mistakes',
          cardButton: {
            target: '',
            url: '/car-buyers/express-lane/first-time-car-buyer-mistakes',
            label: 'Read >',
          },
        },
        {
          id: 'Article25',
          heading: '',
          title: '7 Questions to Ask When Buying a Used Car',
          description: 'Here are seven questions to ask the dealership when buying a used car, from test drives and warranties to costs, terms, financing and more.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/7-question-to-ask-when-buying-a-used-car-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/7-question-to-ask-when-buying-a-used-car-tab.webp',
          imgAlt: '7 Questions to Ask When Buying a Used Car',
          cardButton: {
            target: '',
            url: '/car-buyers/express-lane/questions-for-car-dealers',
            label: 'Read >',
          },
        },
        {
          id: 'Article26',
          heading: '',
          title: '5 Things to Know About Car Dealerships',
          description: 'Car dealerships have solid information on credit scores, trade-in values and financing. Before you visit, here are 5 things to know about car dealerships.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/5-things-to-know-about-car-dealership-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/5-things-to-know-about-car-dealership-tab.webp',
          imgAlt: '5 Things to Know About Car Dealerships',
          cardButton: {
            target: '',
            url: '/car-buyers/express-lane/5-things-to-know-when-visiting-the-dealership',
            label: 'Read >',
          },
        },
        {
          id: 'Article27',
          heading: '',
          title: 'Best Times Of The Year To Buy A Vehicle',
          description: 'One thing that can make a big difference in your car-buying experience — particularly the cost — is the time of year in which you actually purchase your vehicle.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/Best-times-year-buying-a-car-tab-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/Best-times-year-buying-a-car-tab.webp',
          imgAlt: 'Best Times Of The Year To Buy A Vehicle',
          cardButton: {
            target: '',
            url: '/blog/consumer/best-times-of-the-year-to-purchase-a-vehicle',
            label: 'Read >',
          },
        },
        {
          id: 'Article28',
          heading: '',
          title: 'The Right Car For Your Lifestyle',
          description: 'Many folks shop for cars that will meet their daily and/or recreational needs. So our question is, what kind of lifestyle do you lead and what is the car for you?',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/Right-Car-For-Lifestyle-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/Right-Car-For-Lifestyle-tab.webp',
          imgAlt: 'The Right Car For Your Lifestyle',
          cardButton: {
            target: '',
            url: '/blog/consumer/the-right-car-for-your-lifesty-1',
            label: 'Read >',
          },
        },
        {
          id: 'Article29',
          heading: '',
          title: 'Car-Buying Dos And Don’ts',
          description: 'You’re ready to purchase a car but don’t know exactly where to start in the car-buying process. Whether you’re a repeat or first-time car buyer, here are some dos and don’ts that may help you during your car-buying journey.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/Researching-Buying-A-Hybrid-Car-Banner-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/Researching-Buying-A-Hybrid-Car-Banner-tab.webp',
          imgAlt: 'Car-Buying Dos And Don’ts',
          cardButton: {
            target: '',
            url: '/blog/consumer/car-buying-dos-and-don-1',
            label: 'Read >',
          },
        },
        {
          id: 'Article30',
          heading: '',
          title: 'Cost Of Repairing Vs Trading In Your Car',
          description: 'To maintain or trade? That is the question. Here are a few things to consider while determining whether you should keep or trade in your car.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/18 Maintain or Trade final-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/18 Maintain or Trade final-tab.webp',
          imgAlt: 'Cost Of Repairing Vs Trading In Your Car',
          cardButton: {
            target: '',
            url: '/blog/consumer/maintain-or-trade-evaluating-the-cost-of-repairing-vs-trading-in-your-car',
            label: 'Read >',
          },
        },
        {
          id: 'Article31',
          heading: '',
          title: 'Should I Buy A New Or Used Car',
          description: 'Although pre-owned vehicles are usually less expensive than newer models, there are many advantages to buying a new or used car. Let’s have a look, shall we?',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/man-wondering-about-car-he-stands-next-to-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/man-wondering-about-car-he-stands-next-to-tab.webp',
          imgAlt: 'Should I Buy A New Or Used Car',
          cardButton: {
            target: '',
            url: '/blog/consumer/should-i-buy-a-new-or-used-car-',
            label: 'Read >',
          },
        },
        {
          id: 'Article32',
          heading: '',
          title: 'What Are Your Options When Buying A Car',
          description: 'You’re in the market to purchase a vehicle, but can’t decide whether you should go the new or used car buying route. Let’s weigh the options, shall we?',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/thinking-buying-new-car-options-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/thinking-buying-new-car-options-tab.webp',
          imgAlt: 'What Are Your Options When Buying A Car',
          cardButton: {
            target: '',
            url: '/blog/consumer/thinking-of-buying-a-new-or-used-car-let-s-weigh-your-options-',
            label: 'Read >',
          },
        },
        {
          id: 'Article33',
          heading: '',
          title: 'Top Eco-Friendly Cars That Won’t Break The Bank',
          description: 'According to U.S. News & World Report (USNWR), here are some affordable, eco-friendly car options for those in the market to purchase a vehicle.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/electric-vehicle-charging-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/electric-vehicle-charging-tab.webp',
          imgAlt: 'Top Eco-Friendly Cars That Won’t Break The Bank',
          cardButton: {
            target: '',
            url: '/blog/consumer/top-eco-friendly-cars-that-won-t-break-the-bank',
            label: 'Read >',
          },
        },
        {
          id: 'Article34',
          heading: '',
          title: 'Buying A Used Car? Check The Odometer',
          description: 'During the car buying process, knowing the odometer reading of your potential vehicle is imperative — especially if you’re purchasing a used car.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/18 Odometer-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/18 Odometer-tab.webp',
          imgAlt: 'Buying A Used Car? Check The Odometer',
          cardButton: {
            target: '',
            url: '/blog/consumer/why-it-s-important-to-check-the-odometer-before-purchasing-a-used-c-2',
            label: 'Read >',
          },
        },
      ],
    },
  },
  {
    tabType: 'articles',
    tabTitle: 'Credit and Financing',
    active: false,
    tabId: 'tab2',
    tabContent: {
      header: '',
      cardData: [
        {
          id: 'Article35',
          heading: '',
          title: 'Understanding Your Car Payment (Precomputed)',
          description: 'When making your car payment, you may have questions about how much you owe on your vehicle. Here are answers to a few of those questions.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/chalkboard-with-percentage-marks-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/chalkboard-with-percentage-marks-tab.webp',
          imgAlt: 'Understanding Your Car Payment (Precomputed)',
          cardButton: {
            target: '',
            url: '/blog/consumer/understanding-your-car-payment-precomputed-',
            label: 'Read >',
          },
        },
        {
          id: 'Article36',
          heading: '',
          title: 'Get Financed Through An Enrolled Dealer',
          description: 'Credit Acceptance believes everyone deserves a second chance, which is why we enable dealers enrolled on our program to approve everyone, including customers with bad credit history or no credit history at all. Here’s how the program works.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/18 getting financed CACC dealer-lg.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/18 getting financed CACC dealer-tab.webp',
          imgAlt: 'Get Financed Through An Enrolled Dealer',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-it-works-getting-financed-through-a-dealer-enrolled-with-credit-acceptance',
            label: 'Read >',
          },
        },
        {
          id: 'Article37',
          heading: '',
          title: 'How To Rebuild Your Credit After Repossession',
          description: 'Having your car repossessed can have a negative impact on your credit history and stay on your credit report for up to seven years from the original delinquency date.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/couple-look-at-computer-screen-and-smile-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/',
          imgAlt: 'How To Rebuild Your Credit After Repossession',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-rebuild-your-credit-after-repossession',
            label: 'Read >',
          },
        },
        {
          id: 'Article38',
          heading: '',
          title: 'Understanding Your Car Payment (Interest-Bearing)',
          description: 'Have questions about how much you owe on your contract? Here are answers.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/close-up-calculator-toy-car-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/close-up-calculator-toy-car-sm.webp',
          imgAlt: 'Understanding Your Car Payment (Interest-Bearing)',
          cardButton: {
            target: '',
            url: '/blog/consumer/understanding-your-car-payment-interest-bearing-',
            label: 'Read >',
          },
        },
        {
          id: 'Article39',
          heading: '',
          title: 'How To Pay Off Your Car Financing Faster',
          description: 'Paying off your car financing has many benefits, including improving your credit. Here are three ways you can pay off your car faster.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/happy-man-holds-key-in-front-of-car-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/happy-man-holds-key-in-front-of-car-tab.webp',
          imgAlt: 'How To Pay Off Your Car Financing Faster',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-pay-off-your-car-financing-faster',
            label: 'Read >',
          },
        },
        {
          id: 'Article40',
          heading: '',
          title: 'What Is The Minimum Employment Length For Credit Approval',
          description: 'If you have bad credit or no credit, most subprime auto lenders and finance companies will require you to be employed for a certain amount of time. Generally, they prefer at least three months of employment to ensure you’re receiving a steady income.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/happy-couple-stands-in-front-of-new-car-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/happy-couple-stands-in-front-of-new-car-tab.webp',
          imgAlt: 'What Is The Minimum Employment Length For Credit Approval',
          cardButton: {
            target: '',
            url: '/blog/consumer/what-is-the-minimum-employment-length-for-credit-approval-',
            label: 'Read >',
          },
        },
        {
          id: 'Article41',
          heading: '',
          title: 'How To Buy A Car Without A Cosigner',
          description: "While a cosigner can increase your chances of getting credit approval, you can still get approved for auto financing without one.  Here's how.",
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/how-to-buy-a-car-without-a-cosigner-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/how-to-buy-a-car-without-a-cosigner-tab.webp',
          imgAlt: 'How To Buy A Car Without A Cosigner',
          cardButton: {
            target: '',
            url: '/blog/consumer/cosigner',
            label: 'Read >',
          },
        },
        {
          id: 'Article42',
          heading: '',
          title: 'The Ultimate Guide To Buy A Car And Improve Your Credit',
          description: 'If you have bad credit or no credit and are planning to buy a car soon, we’ve created a comprehensive guide to help you along your car buying journey.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/man-holds-car-key-inside-vehicle-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/man-holds-car-key-inside-vehicle-tab.webp',
          imgAlt: 'The Ultimate Guide To Buy A Car And Improve Your Credit',
          cardButton: {
            target: '',
            url: '/blog/consumer/the-ultimate-guide-to-buy-a-car-and-improve-your-credit',
            label: 'Read >',
          },
        },
        {
          id: 'Article43',
          heading: '',
          title: 'Can I Buy A Car With Multiple Repossessions In My Credit History',
          description: 'While having repossessions on your credit report can damage your credit history, it’s not the end of the road. Learn how you can start your credit approval!',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/can-i-buy-car-with-multiple-repossessions-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/can-i-buy-car-with-multiple-repossessions-tab.webp',
          imgAlt: 'Can I Buy A Car With Multiple Repossessions In My Credit History',
          cardButton: {
            target: '',
            url: '/blog/consumer/can-i-buy-a-car-with-multiple-repossessions-in-my-credit-history-',
            label: 'Read >',
          },
        },
        {
          id: 'Article44',
          heading: '',
          title: 'How To Improve Your Credit: Fixing Errors On Your Credit Report',
          description: 'Errors found on your credit report can have a negative impact on your credit history. Learn how you can fix them to improve your credit!',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/woman-at-computer-concentrating-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/woman-at-computer-concentrating-tab.webp',
          imgAlt: 'How To Improve Your Credit: Fixing Errors On Your Credit Report',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-improve-your-credit-fixing-errors-on-your-credit-report',
            label: 'Read >',
          },
        },
        {
          id: 'Article46',
          heading: '',
          title: 'The Difference Between Direct And Indirect Auto Financing',
          description: 'If you’re beginning your car buying journey and plan on getting your vehicle financed, you can either apply for direct or indirect financing. Learn more!',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/close-up-hand-signing-auto-loan-deal-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/close-up-hand-signing-auto-loan-deal-tab.webp',
          imgAlt: 'The Difference Between Direct And Indirect Auto Financing',
          cardButton: {
            target: '',
            url: '/blog/consumer/the-difference-between-direct-and-indirect-auto-financing',
            label: 'Read >',
          },
        },
        {
          id: 'Article47',
          heading: '',
          title: 'Rebuild Credit Through Credit Acceptance',
          description: 'Now that you have vehicle financing, you have a fresh start at building or rebuilding your credit, and the number one way to do this is by paying your bill on time, every time.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/18 financing thru Credit Acceptance-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/18 financing thru Credit Acceptance-tab.webp',
          imgAlt: 'Rebuild Credit Through Credit Acceptance',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-financing-a-car-through-a-dealer-on-the-credit-acceptance-program-can-help-rebuild-your-credit',
            label: 'Read >',
          },
        },
        {
          id: 'Article48',
          heading: '',
          title: "What'S The Difference Between A Car Loan And Auto Financing",
          description: "If you plan on purchasing a vehicle, you have the option of  getting approved for a car loan or auto financing. Here's how they differ.",
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/Car-loan-versus-auto-financing-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/Car-loan-versus-auto-financing-tab.webp',
          imgAlt: "What'S The Difference Between A Car Loan And Auto Financing",
          cardButton: {
            target: '',
            url: '/blog/consumer/what-s-the-difference-between-a-car-loan-and-auto-financing-',
            label: 'Read >',
          },
        },
        {
          id: 'Article49',
          heading: '',
          title: 'What Should I Do If I Keep Getting Turned Down For Auto Financing',
          description: 'There are several reasons why people get turned down for a car loan or auto financing. Learn why and how you can get approved!',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/woman-at-home-worries-over-paperwork-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/woman-at-home-worries-over-paperwork-tab.webp',
          imgAlt: 'What Should I Do If I Keep Getting Turned Down For Auto Financing',
          cardButton: {
            target: '',
            url: '/blog/consumer/what-should-i-do-if-i-keep-getting-turned-down-for-auto-financing-',
            label: 'Read >',
          },
        },
        {
          id: 'Article50',
          heading: '',
          title: 'How to Understanding Simple Interest Car Financing',
          description: 'How to understand simple interest car financing, learn basic financing terms and calculate what you can afford—before you shop for a vehicle.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/understanding-simple-interest-financing-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/understanding-simple-interest-financing-tab.webp',
          imgAlt: 'How to Understanding Simple Interest Car Financing',
          cardButton: {
            target: '',
            url: '/car-buyers/express-lane/auto-financing-101-how-does-interest-work',
            label: 'Read >',
          },
        },
        {
          id: 'Article51',
          heading: '',
          title: 'How To Increase Your Chances Of Getting Approved For Auto Financing',
          description: 'While having good credit is a general requirement to get auto financing, there are ways to increase your chances of getting approved with bad credit.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/car-dealer-shows-customer-car-features-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/car-dealer-shows-customer-car-features-tab.webp',
          imgAlt: 'How To Increase Your Chances Of Getting Approved For Auto Financing',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-increase-your-chances-of-getting-approved-for-auto-financing',
            label: 'Read >',
          },
        },
        {
          id: 'Article52',
          heading: '',
          title: 'Buying A Car With Bad Credit Or No Credit',
          description: 'If you have bad credit or no credit and are looking to buy a car, here are some ways you can get approved for financing and improve your credit.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/couple-holds-key-in-front-of-new-car-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/couple-holds-key-in-front-of-new-car-tab.webp',
          imgAlt: 'Buying A Car With Bad Credit Or No Credit',
          cardButton: {
            target: '',
            url: '/blog/consumer/buying-a-car-with-bad-credit-or-no-credit',
            label: 'Read >',
          },
        },
        {
          id: 'Article53',
          heading: '',
          title: 'How To Get Used Car Financing',
          description: 'If you plan on buying a used car soon, you may be considering your financing options. Here’s how you can get started.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/happy-couple-holds-new-car-key-in-front-of-vehicle-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/happy-couple-holds-new-car-key-in-front-of-vehicle-tab.webp',
          imgAlt: 'How To Get Used Car Financing',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-get-used-car-financing',
            label: 'Read >',
          },
        },
        {
          id: 'Article54',
          heading: '',
          title: 'Rebuilding Your Credit With Bad Credit History',
          description: 'Life may bring financial challenges that can negatively impact your credit history. Here are some ways you can rebuild your credit.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/couple-looks-at-computer-smiling-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/couple-looks-at-computer-smiling-tab.webp',
          imgAlt: 'Rebuilding Your Credit With Bad Credit History',
          cardButton: {
            target: '',
            url: '/blog/consumer/rebuilding-your-credit-with-bad-credit-history',
            label: 'Read >',
          },
        },
        {
          id: 'Article55',
          heading: '',
          title: 'Signs You’re Falling Into A Bad Credit Cycle',
          description: 'If you have bad credit, chances are you’ve fallen into a cycle of poor spending habits. Here are three signs of bad credit and some ways to improve it.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/worried-woman-looks-at-computer-screen-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/worried-woman-looks-at-computer-screen-tab.webp',
          imgAlt: 'Signs You’re Falling Into A Bad Credit Cycle',
          cardButton: {
            target: '',
            url: '/blog/consumer/signs-you-re-falling-into-a-bad-credit-cycle',
            label: 'Read >',
          },
        },
        {
          id: 'Article56',
          heading: '',
          title: 'What Factors Affect My Car Payments',
          description: 'Since buying a car is a major investment, it’s important to know what factors go into determining your monthly car payments. Learn more!',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/toy-car-on-calendar-with-payment-date-circled-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/toy-car-on-calendar-with-payment-date-circled-tab.webp',
          imgAlt: 'What Factors Affect My Car Payments',
          cardButton: {
            target: '',
            url: '/blog/consumer/what-factors-affect-my-car-payments-',
            label: 'Read >',
          },
        },
        {
          id: 'Article57',
          heading: '',
          title: 'Leasing Vs Auto Financing',
          description: 'Deciding whether you should finance or lease your next (or first) car can be tough, but there’s a big difference between the two.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/19-1_LeasingVsFinancing_BlogBanner-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/19-1_LeasingVsFinancing_BlogBanner-tab.webp',
          imgAlt: 'Leasing Vs Auto Financing',
          cardButton: {
            target: '',
            url: '/blog/consumer/the-difference-between-leasing-and-auto-financi-1',
            label: 'Read >',
          },
        },
        {
          id: 'Article58',
          heading: '',
          title: 'Auto Financing 101: How Does Interest Work?',
          description: 'Ready to start the car-buying journey? Learn how interest rates work when financing a car and how it’s calculated into your monthly car payment.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/young-man-learning-about-auto-finance-interest-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/young-man-learning-about-auto-finance-interest-tab.webp',
          imgAlt: 'Auto Financing 101: How Does Interest Work?',
          cardButton: {
            target: '',
            url: '/blog/consumer/auto-financing-101-how-does-interest-work-',
            label: 'Read >',
          },
        },
        {
          id: 'Article59',
          heading: '',
          title: 'How Auto Financing Can Impact Your Credit History',
          description: 'Getting a car loan or auto financing to purchase a vehicle can be a good way to establish a positive credit history. Learn how!',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/woman-looks-at-computer-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/woman-looks-at-computer-tab.webp',
          imgAlt: 'How Auto Financing Can Impact Your Credit History',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-auto-financing-can-impact-your-credit-history',
            label: 'Read >',
          },
        },
        {
          id: 'Article60',
          heading: '',
          title: 'How To Improve Your Credit: Establishing Credit History',
          description: 'How can you establish credit as a first-time car buyer? Learn how to start your credit approval and start building your credit history.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/woman-applying-for-subprime-financing-in-order-to-build-credit-history-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/woman-applying-for-subprime-financing-in-order-to-build-credit-history-tab.webp',
          imgAlt: 'How To Improve Your Credit: Establishing Credit History',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-improve-your-credit-establishing-credit-history',
            label: 'Read >',
          },
        },
        {
          id: 'Article61',
          heading: '',
          title: 'How To Improve Your Credit: Budgeting',
          description: "Since budgeting gives you a clear understanding of what you can or can't afford, following these steps can help you improve your credit.",
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/How-to-improve-your-credit-budgeting-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/How-to-improve-your-credit-budgeting-tab.webp',
          imgAlt: 'How To Improve Your Credit: Budgeting',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-improve-your-credit-budgeting',
            label: 'Read >',
          },
        },
        {
          id: 'Article62',
          heading: '',
          title: 'Check Your Credit Score Before Buying',
          description: 'Regardless of whether you have good or bad credit, it’s helpful to review your credit report before purchasing a vehicle. Knowing your credit score in advance can improve your car buying experience because you know what to expect when trying to get a loan or financing for a vehicle.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/18 Checking Credit Score-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/18 Checking Credit Score-tab.webp',
          imgAlt: 'Check Your Credit Score Before Buying',
          cardButton: {
            target: '',
            url: '/blog/consumer/should-you-check-your-credit-score-before-purchasing-a-vehicle-',
            label: 'Read >',
          },
        },
        {
          id: 'Article63',
          heading: '',
          title: 'How Protecting Yourself Against Fraud Can Protect Your Credit',
          description: 'Protecting your identity is an important part of protecting your credit. Here are some prevention steps to protect yourself from identity theft.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/couple-looks-at-computer-screen-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/couple-looks-at-computer-screen-tab.webp',
          imgAlt: 'How Protecting Yourself Against Fraud Can Protect Your Credit',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-protecting-yourself-against-fraud-can-protect-your-credit',
            label: 'Read >',
          },
        },
        {
          id: 'Article64',
          heading: '',
          title: 'How To Improve Your Credit: Paying Down Debt',
          description: 'While making on-time payments is a good way to improve your credit, reducing the amount of debt you owe can help as well.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/woman-paying-down-debt-to-improve-her-credit-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/woman-paying-down-debt-to-improve-her-credit-tab.webp',
          imgAlt: 'How To Improve Your Credit: Paying Down Debt',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-improve-your-credit-paying-down-debt',
            label: 'Read >',
          },
        },
        {
          id: 'Article65',
          heading: '',
          title: 'Determining Your Monthly Car Payment',
          description: 'It’s wise to put together a budget that will help you determine a monthly car payment that makes you comfortable. Below are some ways you can get started.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/18 Determining Monthly Payment-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/18 Determining Monthly Payment-tab.webp',
          imgAlt: 'Determining Your Monthly Car Payment',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-determine-your-monthly-car-payment-when-purchasing-a-vehic-2',
            label: 'Read >',
          },
        },
        {
          id: 'Article66',
          heading: '',
          title: 'A Complete Auto Financing Guide For First-Time Car Buyers',
          description: 'While buying your first car is exciting, it can also be overwhelming. Learn car buying steps that can help you during your car-buying journey!',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/first-time-buyer-who-got-advice-about-financing-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/first-time-buyer-who-got-advice-about-financing-tab.webp',
          imgAlt: 'A Complete Auto Financing Guide For First-Time Car Buyers',
          cardButton: {
            target: '',
            url: '/blog/consumer/a-complete-auto-financing-guide-for-first-time-car-buyers',
            label: 'Read >',
          },
        },
        {
          id: 'Article67',
          heading: '',
          title: 'Good Vs. Bad Ways To Use Credit',
          description: 'Credit is a powerful tool that enables you to build a good credit history and finance large purchases and investments (such as buying a car or home) with ease.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/couple-shops-online-with-credit-card-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/couple-shops-online-with-credit-card-tab.webp',
          imgAlt: 'Good Vs. Bad Ways To Use Credit',
          cardButton: {
            target: '',
            url: '/blog/consumer/good-vs-bad-ways-to-use-credit',
            label: 'Read >',
          },
        },
        {
          id: 'Article68',
          heading: '',
          title: 'What To Know When Applying For Auto Financing',
          description: 'Knowing your financing options is key when shopping for your next car. Here’s what you should know when applying for auto financing.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/man-works-on-laptop-computer-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/man-works-on-laptop-computer-tab.webp',
          imgAlt: 'What To Know When Applying For Auto Financing',
          cardButton: {
            target: '',
            url: '/blog/consumer/what-to-know-when-applying-for-auto-financing',
            label: 'Read >',
          },
        },
        {
          id: 'Article69',
          heading: '',
          title: 'How to Build Your Credit History',
          description: 'Building or reestablishing your credit can be tricky. Maybe you’re a first-time car buyer with no credit history established, or someone who currently has bad credit and recently filed for bankruptcy.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/how-to-build-your-credit-history-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/how-to-build-your-credit-history-tab.webp',
          imgAlt: 'How to Build Your Credit History',
          cardButton: {
            target: '',
            url: '/car-buyers/express-lane/5-ways-to-build-or-reestablish-your-credit-history',
            label: 'Read >',
          },
        },
        {
          id: 'Article70',
          heading: '',
          title: 'What Is The Difference Between My Credit Report And Credit Score',
          description: 'It’s common to confuse checking your credit report with checking your credit score. However, the two are not one in the same. Let’s take a look at how they differ.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/Confused-Credit-Consumer-Banner-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/Confused-Credit-Consumer-Banner-tab.webp',
          imgAlt: 'What Is The Difference Between My Credit Report And Credit Score',
          cardButton: {
            target: '',
            url: '/blog/consumer/what-is-the-difference-between-my-credit-report-and-credit-score-',
            label: 'Read >',
          },
        },
        {
          id: 'Article71',
          heading: '',
          title: 'Get Approved To Finance Your Next Car',
          description: 'Many people with bad credit or no credit who try to get approved for financing often hear “no” from auto lenders and finance companies. But everyone deserves a second chance to improve their credit, get approved for vehicle financing, and purchase a reliable car.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/18 second chance finance approval-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/18 second chance finance approval-tab.webp',
          imgAlt: 'Get Approved To Finance Your Next Car',
          cardButton: {
            target: '',
            url: '/blog/consumer/3-simple-steps-to-start-your-approval-for-your-next-car',
            label: 'Read >',
          },
        },
        {
          id: 'Article72',
          heading: '',
          title: '5 Common Credit Score Myths Debunked',
          description: 'To manage and improve personal credit, knowing how the system works and debunking common myths is important. Here are five typical misconceptions.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/5-common-credit-score-myths-debunked-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/5-common-credit-score-myths-debunked-tab.webp',
          imgAlt: '5 Common Credit Score Myths Debunked',
          cardButton: {
            target: '',
            url: '/car-buyers/express-lane/credit-myths-debunked',
            label: 'Read >',
          },
        },
        {
          id: 'Article73',
          heading: '',
          title: 'Do Taxes Affect Your Credit Score?',
          description: "Although your tax information generally isn’t reported to the credit bureaus, there is a way it can show up in your credit history. Here's how.",
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/do-taxes-affect-your-credit-score-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/do-taxes-affect-your-credit-score-tab.webp',
          imgAlt: 'Do Taxes Affect Your Credit Score?',
          cardButton: {
            target: '',
            url: '/blog/consumer/do-taxes-affect-your-credit-score-',
            label: 'Read >',
          },
        },
        {
          id: 'Article74',
          heading: '',
          title: 'How Do I Know If I Have Bad Credit Or No Credit?',
          description: 'Knowing your credit is an important step in the car-buying process. Learn how you can check your credit and get started on your credit approval.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/Confused-About-Bad-Credit-Banner-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/Confused-About-Bad-Credit-Banner-tab.webp',
          imgAlt: 'How Do I Know If I Have Bad Credit Or No Credit?',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-do-i-know-if-i-have-bad-credit-or-no-credit-',
            label: 'Read >',
          },
        },
        {
          id: 'Article75',
          heading: '',
          title: 'How To Build Your Credit History After College',
          description: 'If you’re a recent college grad, you probably don’t have much credit history established. Here’s how you can start building your credit!',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/young-man-in-graduation-cap-needs-to-build-credit-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/young-man-in-graduation-cap-needs-to-build-credit-tab.webp',
          imgAlt: 'How To Build Your Credit History After College',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-build-your-credit-history-after-college',
            label: 'Read >',
          },
        },
        {
          id: 'Article76',
          heading: '',
          title: 'How To Rebuild Your Credit After Bankruptcy',
          description: 'If you are someone who has recently filed bankruptcy at the hands of the COVID-19 pandemic, here are a few suggestions for how you can start to rebuild your credit.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/happy-man-looking-at-computer-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/happy-man-looking-at-computer-tab.webp',
          imgAlt: 'How To Rebuild Your Credit After Bankruptcy',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-rebuild-your-credit-after-bankruptcy',
            label: 'Read >',
          },
        },
        {
          id: 'Article77',
          heading: '',
          title: 'Setting Goals That May Help Your Credit',
          description: 'People don’t plan to have bad credit, but it happens to the best of us. That’s why it’s important to set financial goals and take the necessary steps to stay on track towards maintaining or improving your credit.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/financial-goals-improve-credit-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/financial-goals-improve-credit-tab.webp',
          imgAlt: 'Setting Goals That May Help Your Credit',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-set-realistic-financial-goals-that-may-help-improve-your-credit',
            label: 'Read >',
          },
        },
        {
          id: 'Article78',
          heading: '',
          title: 'Why You Should Know Your Credit History Before Buying A Car',
          description: 'Shopping for the perfect car and going for test drives may be fun and all but knowing your credit history can be helpful to know if you plan on applying for auto financing to buy a car.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/checking-credit-history-on-mobile-phone-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/checking-credit-history-on-mobile-phone-tab.webp',
          imgAlt: 'Why You Should Know Your Credit History Before Buying A Car',
          cardButton: {
            target: '',
            url: '/blog/consumer/why-you-should-know-your-credit-history-before-buying-a-car',
            label: 'Read >',
          },
        },
      ],
    },
  },
  {
    tabType: 'articles',
    tabTitle: 'Car Maintenance and Care',
    active: false,
    tabId: 'tab3',
    tabContent: {
      header: '',
      cardData: [
        {
          id: 'Article79',
          heading: '',
          title: 'Why Is A Car Title Important?',
          description: 'When you buy a car in the U.S., you receive a car title. Here’s what to know about car titles and why they’re important.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/new-car-owner-signs-paperwork-gets-handed-keys-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/new-car-owner-signs-paperwork-gets-handed-keys-tab.webp',
          imgAlt: 'Why Is A Car Title Important?',
          cardButton: {
            target: '',
            url: '/blog/consumer/why-is-a-car-title-important-',
            label: 'Read >',
          },
        },
        {
          id: 'Article80',
          heading: '',
          title: 'How To Protect Your Car From Getting Stolen',
          description: 'While auto theft isn’t as common as it once was, you should still take the proper precautions to protect yourself from auto theft. Learn how!',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/close-up-club-on-steering-wheel-lg.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/close-up-club-on-steering-wheel-tab.webp',
          imgAlt: 'How To Protect Your Car From Getting Stolen',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-protect-your-car-from-getting-stolen',
            label: 'Read >',
          },
        },
        {
          id: 'Article81',
          heading: '',
          title: 'How To Register Your Vehicle',
          description: 'Registering your vehicle with your state proves you own drive your car. If you’re registering for the first time, here’s how to get started.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/man-holds-car-registration-and-car-keys-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/man-holds-car-registration-and-car-keys-tab.webp',
          imgAlt: 'How To Register Your Vehicle',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-register-your-vehicle',
            label: 'Read >',
          },
        },
        {
          id: 'Article82',
          heading: '',
          title: 'How To Prep Your Car For The Fall And Winter Weather',
          description: 'With the end of summer near and cooler weather approaching, it may be a good time to start prepping your vehicle for the upcoming fall and winter seasons. Colder temperatures can take a toll on things like your car’s tire traction and windshield durability.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/man-pours-windshield-fluid-in-the-snow-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/man-pours-windshield-fluid-in-the-snow-tab.webp',
          imgAlt: 'How To Prep Your Car For The Fall And Winter Weather',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-prep-your-car-for-the-fall-and-winter-weather',
            label: 'Read >',
          },
        },
        {
          id: 'Article83',
          heading: '',
          title: 'How To Keep Your Windshield From Freezing During The Winter',
          description: 'There’s nothing like walking to your car on a cold, winter day to find an icy windshield. Here are some tips to prevent your car windshield from freezing.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/person-scraping-frozen-windshield-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/person-scraping-frozen-windshield-tab.webp',
          imgAlt: 'How To Keep Your Windshield From Freezing During The Winter',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-keep-your-windshield-from-freezing-during-the-winter',
            label: 'Read >',
          },
        },
        {
          id: 'Article84',
          heading: '',
          title: 'How To Reduce Your Vehicle Wear And Tear With Car Maintenance',
          description: 'While vehicle wear and tear is inevitable, there are several ways you can minimize it. Read on for our car maintenance tips!',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/close-up-of-man-performing-vehicle-maintenance-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/close-up-of-man-performing-vehicle-maintenance-tab.webp',
          imgAlt: 'How To Reduce Your Vehicle Wear And Tear With Car Maintenance',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-reduce-your-vehicle-wear-and-tear-with-car-maintenance',
            label: 'Read >',
          },
        },
        {
          id: 'Article85',
          heading: '',
          title: 'How Often Should You Get Your Tires Rotated?',
          description: 'Tire rotations are an important part of your car maintenance routine. Find out why it’s important and how often you should get your tires rotated.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/four-tires-rolling-down-a-road-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/four-tires-rolling-down-a-road-tab.webp',
          imgAlt: 'How Often Should You Get Your Tires Rotated?',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-often-should-you-get-your-tires-rotated-',
            label: 'Read >',
          },
        },
        {
          id: 'Article86',
          heading: '',
          title: 'How Can I Fix The Rust On My Used Car?',
          description: 'Since rust forms in stages, it’s important to know what type of rust your vehicle has so you can properly address it. If not addressed immediately, rust can spread and potentially do long-term damage to your vehicle.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/close-up-rusty-bottom-edge-of-vehicle-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/close-up-rusty-bottom-edge-of-vehicle-tab.webp',
          imgAlt: 'How Can I Fix The Rust On My Used Car?',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-can-i-fix-the-rust-on-my-used-car-',
            label: 'Read >',
          },
        },
        {
          id: 'Article87',
          heading: '',
          title: 'How Often Should You Change Your Oil?',
          description: 'Getting an oil change is an important part of your car maintenance routine. Read on to see how often you should change your oil.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/close-up-pouring-oil-into-vehicle-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/close-up-pouring-oil-into-vehicle-tab.webp',
          imgAlt: 'How Often Should You Change Your Oil?',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-often-should-you-change-your-oil-',
            label: 'Read >',
          },
        },
        {
          id: 'Article88',
          heading: '',
          title: 'How Often Should You Get A Car Wash?',
          description: 'Experts say the general rule of thumb is to get your car washed every two weeks, but the frequency can increase or decrease depending on your circumstances.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/vehicle-in-an-automatic-car-wash-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/vehicle-in-an-automatic-car-wash-tab.webp',
          imgAlt: 'How Often Should You Get A Car Wash?',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-often-should-you-get-a-car-wash-',
            label: 'Read >',
          },
        },
        {
          id: 'Article89',
          heading: '',
          title: 'How Often Should You Get Your Car Detailed?',
          description: 'Getting your car detailed is an effective way to keep it fresh and clean on a regular basis. Learn how often you should detail your car!',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/man-using-car-buffing-machine-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/man-using-car-buffing-machine-tab.webp',
          imgAlt: 'How Often Should You Get Your Car Detailed?',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-often-should-you-get-your-car-detailed-',
            label: 'Read >',
          },
        },
        {
          id: 'Article90',
          heading: '',
          title: 'How To Change A Flat Tire',
          description: 'Knowing how to change your tires is one of the bare necessities of driving. If you’ve never learned how, here’s a step-by-step process.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/close-up-woman-changing-flat-tire-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/close-up-woman-changing-flat-tire-tab.webp',
          imgAlt: 'How To Change A Flat Tire',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-change-a-flat-tire',
            label: 'Read >',
          },
        },
        {
          id: 'Article91',
          heading: '',
          title: 'How To Clean Your Car’s Engine',
          description: 'If you’ve never given your car engine a good cleaning, here’s a step-by-step process to help you get started.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/open-car-hood-clean-engine-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/open-car-hood-clean-engine-tab.webp',
          imgAlt: 'How To Clean Your Car’s Engine',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-clean-your-car-s-engine',
            label: 'Read >',
          },
        },
        {
          id: 'Article92',
          heading: '',
          title: 'How To Keep Your Parked Car Cool During The Summer',
          description: 'Here are four tricks to skirt around those scalding-hot mini hazards and keep your car cool in the summer.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/sun-shade-in-car-windshield-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/sun-shade-in-car-windshield-tab.webp',
          imgAlt: 'How To Keep Your Parked Car Cool During The Summer',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-keep-your-parked-car-cool-during-the-summer',
            label: 'Read >',
          },
        },
        {
          id: 'Article93',
          heading: '',
          title: 'Key Information You’ll Find In Your Car Manual',
          description: 'Whether you purchase a new or used vehicle, every car should come with an owner’s manual to help you operate and/or troubleshoot your vehicle correctly. This instructional guide is filled with a ton of information, which can be overwhelming.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/woman-reads-car-manual-over-open-car-hood-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/woman-reads-car-manual-over-open-car-hood-tab.webp',
          imgAlt: 'Key Information You’ll Find In Your Car Manual',
          cardButton: {
            target: '',
            url: '/blog/consumer/key-information-you-ll-find-in-your-car-manual',
            label: 'Read >',
          },
        },
      ],
    },
  },
  {
    tabType: 'articles',
    tabTitle: 'For Fun',
    active: false,
    tabId: 'tab4',
    tabContent: {
      header: '',
      cardData: [
        {
          id: 'Article94',
          heading: '',
          title: 'Will Self-Driving Cars Replace Human-Operated Cars?',
          description: 'While driverless cars are predicted to be the transportation of the future, there are levels to this. Learn more!',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/close-up-autonomous-drive-button-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/close-up-autonomous-drive-button-tab.webp',
          imgAlt: 'Will Self-Driving Cars Replace Human-Operated Cars?',
          cardButton: {
            target: '',
            url: '/blog/consumer/will-self-driving-cars-replace-human-operated-cars-',
            label: 'Read >',
          },
        },
        {
          id: 'Article95',
          heading: '',
          title: 'Strangest-Looking Cars Of All Time',
          description: 'Ever seen a car so strange looking that you do a double take? Check out some of these top-ranked unique cars by U.S. News!',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/amphibious-car-in-lake-lg.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/amphibious-car-in-lake-tab.webp',
          imgAlt: 'Strangest-Looking Cars Of All Time',
          cardButton: {
            target: '',
            url: '/blog/consumer/strangest-looking-cars-of-all-time',
            label: 'Read >',
          },
        },
        {
          id: 'Article96',
          heading: '',
          title: '5 Foods You Can Eat In Your Car Without Making A Mess',
          description: 'Eating in the car can be tricky. You don’t want to make a mess, but there are times you may get hungry and need a little snack for the road. Luckily, there are several foods you can eat that are car-friendly and healthy, too!',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/couple-eats-while-sitting-in-hatchback-of-parked-car-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/couple-eats-while-sitting-in-hatchback-of-parked-car-tab.webp',
          imgAlt: '5 Foods You Can Eat In Your Car Without Making A Mess',
          cardButton: {
            target: '',
            url: '/blog/consumer/5-foods-you-can-eat-in-your-car-without-making-a-mess',
            label: 'Read >',
          },
        },
        {
          id: 'Article97',
          heading: '',
          title: '5 Car Gift Ideas For The Holidays',
          description: 'While the holidays are great for spending quality time with family and friends, finding the perfect gift for your friends and family can be a bit of a hassle. To alleviate some of the pressure that comes with shopping for holiday presents, here are some car-gifting ideas your loved ones may appreciate.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/Car-Sketch-Car-Gift-Idea-Banner-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/Car-Sketch-Car-Gift-Idea-Banner-tab.webp',
          imgAlt: '5 Car Gift Ideas For The Holidays',
          cardButton: {
            target: '',
            url: '/blog/consumer/5-car-gift-ideas-for-the-holidays',
            label: 'Read >',
          },
        },
        {
          id: 'Article98',
          heading: '',
          title: '6 Road Trip Routes For The Summer',
          description: 'The warm weather and sunshine have finally arrived, which means #RoadTripSeason is in full effect. If you recently purchased a vehicle, what better way to kick off the summer in your new ride than to hit the open road with your family or close group of friends?',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/Road-Trip-Planner-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/Road-Trip-Planner-tab.webp',
          imgAlt: '6 Road Trip Routes For The Summer',
          cardButton: {
            target: '',
            url: '/blog/consumer/6-road-trip-routes-for-the-summer',
            label: 'Read >',
          },
        },
        {
          id: 'Article99',
          heading: '',
          title: 'Making Tailgating Kits For Your Car',
          description: 'Before the game, cars pack into parking lots and tailgaters transform their new or used cars into mobile gathering venues. Here are some ideas to make your car the pre-game hot spot.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/tailgating-truck-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/tailgating-truck-tab.webp',
          imgAlt: 'Making Tailgating Kits For Your Car',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-make-the-perfect-tailgating-kit-for-your-car',
            label: 'Read >',
          },
        },
        {
          id: 'Article100',
          heading: '',
          title: 'Price You Pay For “Free” Winning A Car',
          description: 'Winning a car sounds appealing, especially when you need a car and have trouble getting an auto loan or financing due to bad credit or no credit. But, when it comes to winning a car, it’s not as simple as being handed a shiny set of keys and driving home in your new freebie.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/18-6_CanYouAffordFree_BlogBanner-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/18-6_CanYouAffordFree_BlogBanner-tab.webp',
          imgAlt: 'Price You Pay For “Free” Winning A Car',
          cardButton: {
            target: '',
            url: '/blog/consumer/the-price-you-pay-for-free-winning-a-car-on-a-gameshow',
            label: 'Read >',
          },
        },
        {
          id: 'Article101',
          heading: '',
          title: 'Top Dog-Friendly Cars Of 2021',
          description: 'Here are a some of the top cars for dogs and their chauffeurs based on size, space, safety, reliability and more!',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/dog-in-car-window-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/dog-in-car-window-tab.webp',
          imgAlt: 'Top Dog-Friendly Cars Of 2021',
          cardButton: {
            target: '',
            url: '/blog/consumer/top-dog-friendly-cars-of-2021',
            label: 'Read >',
          },
        },
        {
          id: 'Article102',
          heading: '',
          title: 'Trunk Or Treat Car Decorating Tips',
          description: 'If you’re thinking about participating in a trunk-or-treat event this year, here are some cool decorating themes we found on Pinterest to get your creative juices flowing.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/Trunk-or-treat-car-ideas-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/Trunk-or-treat-car-ideas-tab.webp',
          imgAlt: 'Trunk Or Treat Car Decorating Tips',
          cardButton: {
            target: '',
            url: '/blog/consumer/trunk-or-treat-decorating-ideas-for-your-car',
            label: 'Read >',
          },
        },
      ],
    },
  },
  {
    tabType: 'articles',
    tabTitle: 'Driving and Safety',
    active: false,
    tabId: 'tab5',
    tabContent: {
      header: '',
      cardData: [
        {
          id: 'Article103',
          heading: '',
          title: 'How Much Time Do You Spend In Your Car?',
          description: 'Between commuting to and from work, chauffeuring the little ones between school and extracurricular activities, taking trips to the grocery store, and running weekend errands, the amount of time we spend in our cars adds up. So, how much time is that, exactly?',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/happy-man-drives-car-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/happy-man-drives-car-tab.webp',
          imgAlt: 'How Much Time Do You Spend In Your Car?',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-much-time-do-you-spend-in-your-car-',
            label: 'Read >',
          },
        },
        {
          id: 'Article104',
          heading: '',
          title: 'How To Calculate The Gas Cost Of A Road Trip',
          description: 'While road trips are usually the go-to alternative for travel on a budget, costs add up. Here’s how to calculate the cost of your road trip.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/hand-holding-gas-pump-handle-into-car-lg.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/hand-holding-gas-pump-handle-into-car-tab.webp',
          imgAlt: 'How To Calculate The Gas Cost Of A Road Trip',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-calculate-the-gas-cost-of-a-road-trip',
            label: 'Read >',
          },
        },
        {
          id: 'Article105',
          heading: '',
          title: 'How Getting Into A Car Accident Can Affect Your Auto Insurance',
          description: 'Getting into a car accident is one of life’s potential hassles. To add insult to injury (hopefully, no pun intended), it’s highly likely your insurance premium will increase once an accident is on your record, regardless of who’s at fault.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/man-uses-phone-in-front-of-car-accident-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/man-uses-phone-in-front-of-car-accident-tab.webp',
          imgAlt: 'How Getting Into A Car Accident Can Affect Your Auto Insurance',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-getting-into-a-car-accident-can-affect-your-auto-insurance',
            label: 'Read >',
          },
        },
        {
          id: 'Article106',
          heading: '',
          title: 'What Happens If You Crash A Car During A Test Drive?',
          description: 'So, what happens if you get into an accident while test driving a car?',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/woman-phones-for-help-after-car-accident-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/woman-phones-for-help-after-car-accident-tab.webp',
          imgAlt: 'What Happens If You Crash A Car During A Test Drive?',
          cardButton: {
            target: '',
            url: '/blog/consumer/what-happens-if-you-crash-a-car-during-a-test-drive-',
            label: 'Read >',
          },
        },
        {
          id: 'Article107',
          heading: '',
          title: 'How To Parallel Park Your Car',
          description: 'Parallel parking can be a learning curve for many new drivers. Here are four steps on how to parallel park your car.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/parallel-parking-graphic-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/parallel-parking-graphic-tab.webp',
          imgAlt: 'How To Parallel Park Your Car',
          cardButton: {
            target: '',
            url: '/blog/consumer/how-to-parallel-park-your-car',
            label: 'Read >',
          },
        },
        {
          id: 'Article108',
          heading: '',
          title: 'Top Car Safety Features For Teen Drivers',
          description: 'Having a new teen driver on the road for the first time can be nerve wracking. Here are the best vehicle safety features that will help give you peace of mind.',
          imgURL: 'AWS_BUCKET_URL/www/customer-blogs/images/man-teaching-teen-son-to-drive-sm.webp',
          tabletImgUrl: 'AWS_BUCKET_URL/www/customer-blogs/images/man-teaching-teen-son-to-drive-tab.webp',
          imgAlt: 'Top Car Safety Features For Teen Drivers',
          cardButton: {
            target: '',
            url: '/blog/consumer/top-car-safety-features-for-teen-drivers',
            label: 'Read >',
          },
        },
      ],
    },
  },
];
